#!/usr/bin/env bash

main () {
  card_numbers="$1"
  num_digits=${#card_numbers}

  k=0
  for ((i=$num_digits-1;i>=0;i--)); do
    digit=${card_numbers:i:1}

    if [[ k%2 ]]

    ((k=k+1))
  done
}

main "$@"
