#!/usr/bin/env bash

main () {
  text="$1"
  text_size=${#text}
  ((text_size=$text_size-1))

  echo $text_size

  for ((i=$text_size;i>=0;i--)); do
    echo $i
    printf "%s", "$i"
  done
}

main "$@"
